package lk.ijse.MilkBar.util;

public enum Routes {
    CUSTOMER,EMPLOYEE,SUPPLIER,ITEM,CUSTOMER_ORDER_DETAILS,PAYMENT,ADMIN_DASHBOARD,USER,RECEPTION_DASHBOARD,LOGOUT,REPORT,HOME,CUSTOMER_PAYMENT,SUPPLIER_PAYMENT
}
